settings:
  name: "Satori CLI Tests"
  log: slack, discord, email, telegram
  image: public.ecr.aws/docker/library/python:3.9-slim-bullseye

import:
  - "satori://secrets/semgrep.yml"
test:
  assertReturnCode: 0
  assertStderrNotContains: Traceback
